version: 2

sources:
  - name: staging
    database: "{{ env_var('DBT_DATABASE', 'my-dbt-project-875462') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'trips_data_all') }}"
      # loaded_at_field: record_loaded_at
    tables:
      - name: ext_green_taxi
      - name: ext_yellow_taxi

       # freshness:
           # error_after: {count: 6, period: hour}